# Generated by Django 5.0.6 on 2024-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0003_orderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='Date',
            field=models.CharField(max_length=50),
        ),
    ]
