# Generated by Django 5.0.6 on 2024-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0005_alter_orderevent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='Price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
