# Generated by Django 5.0.6 on 2024-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0006_alter_orderevent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='Price',
            field=models.CharField(max_length=50),
        ),
    ]
