# Generated by Django 5.0.6 on 2024-05-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0007_alter_orderevent_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_Name', models.CharField(max_length=50)),
                ('CAT_IMID', models.CharField(max_length=50)),
                ('FD_ID', models.CharField(max_length=50)),
                ('Train_Session', models.CharField(max_length=50)),
                ('FileName', models.CharField(max_length=50)),
                ('FileType', models.CharField(max_length=50)),
                ('Status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
