# Generated by Django 5.0.6 on 2024-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0008_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Event', models.CharField(max_length=50)),
                ('Fix_Col_0', models.CharField(max_length=50)),
                ('FirmROID', models.CharField(max_length=50)),
                ('MsgType', models.CharField(max_length=50)),
                ('CAT_IM_ID', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Order_ID', models.CharField(max_length=50)),
                ('Symbol', models.CharField(max_length=50)),
                ('TimeStamp', models.CharField(max_length=50)),
                ('Fix_Col_1', models.CharField(max_length=50)),
                ('Fix_Col_2', models.CharField(max_length=50)),
                ('Fix_Col_3', models.CharField(max_length=50)),
                ('Fix_Col_4', models.CharField(max_length=50)),
                ('Fix_Col_5', models.CharField(max_length=50)),
                ('Fix_Col_6', models.CharField(max_length=50)),
                ('Fix_Col_7', models.CharField(max_length=50)),
                ('Fix_Col_8', models.CharField(max_length=50)),
                ('SideType', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Fix_Col_9', models.CharField(max_length=50)),
                ('OrderType', models.CharField(max_length=50)),
                ('TIF', models.CharField(max_length=50)),
                ('Trading_Session', models.CharField(max_length=50)),
                ('Fix_Col_10', models.CharField(max_length=50)),
                ('Fix_Col_11', models.CharField(max_length=50)),
                ('FD_ID', models.CharField(max_length=50)),
                ('Acc_Type', models.CharField(max_length=50)),
                ('Fix_Col_12', models.CharField(max_length=50)),
                ('Fix_Col_13', models.CharField(max_length=50)),
                ('Fix_Col_14', models.CharField(max_length=50)),
                ('Fix_Col_15', models.CharField(max_length=50)),
                ('Fix_Col_16', models.CharField(max_length=50)),
                ('Fix_Col_17', models.CharField(max_length=50)),
                ('Fix_Col_18', models.CharField(max_length=50)),
                ('Fix_Col_19', models.CharField(max_length=50)),
                ('Fix_Col_20', models.CharField(max_length=50)),
                ('Fix_Col_21', models.CharField(max_length=50)),
                ('Fix_Col_22', models.CharField(max_length=50)),
                ('Fix_Col_23', models.CharField(max_length=50)),
                ('Fix_Col_24', models.CharField(max_length=50)),
                ('Fix_Col_25', models.CharField(max_length=50)),
                ('Fix_Col_26', models.CharField(max_length=50)),
                ('Fix_Col_27', models.CharField(max_length=50)),
                ('Fix_Col_28', models.CharField(max_length=50)),
            ],
        ),
    ]
