# Generated by Django 5.0.6 on 2024-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0009_eoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
