# Generated by Django 5.0.6 on 2024-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixApp', '0010_fixtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtags',
            name='tag_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
